name: Test Build on All Platforms

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^3.11.0"

      - name: Set up Linux dependencies 
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.os == 'ubuntu-latest'
        with:
          packages: clang libgtk-3-dev xvfb

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v4 
        with:
          channel: stable
          cache-sdk: true
          cache: true

      - name: Get Flutter info
        run: flutter doctor -v

      - name: Test Linux build
        if: matrix.os == 'ubuntu-latest'
        working-directory: minisound/example/
        run: |
          flutter build linux --debug

          tree build/linux/x64

          xvfb-run -w0 build/linux/x64/debug/bundle/example &
          sleep 5 && pkill -TERM example

      - name: Test Windows build
        if: matrix.os == 'windows-latest'
        working-directory: minisound/example/
        run: |
          flutter build windows --debug

          cd build\windows\x64
          tree /F
          cd -

          $PROC = Start-Process -FilePath build\windows\x64\runner\Debug\example.exe -PassThru
          Start-Sleep -Seconds 5
          $PROC.CloseMainWindow()

      - name: Test MacOS build
        if: matrix.os == 'macos-latest'
        working-directory: minisound/example/
        run: |
          flutter build macos --debug

          tree build/macos/x64
