name: Test Build on All Platforms

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^3.11.0"

      - name: Set up Linux Flutter dependencies 
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.os == 'ubuntu-latest'
        with:
          packages: clang libgtk-3-dev

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v4 
        with:
          channel: stable
          cache-sdk: true
          cache: true

      - name: Test Linux build
        if: matrix.os == 'ubuntu-latest'
        working-directory: minisound/example/
        run: |
          flutter doctor -v
          flutter build linux --debug

          flutter run 

          cd build\linux\x64
          tree

      - name: Test Windows build
        if: matrix.os == 'windows-latest'
        working-directory: minisound/example/
        run: |
          flutter doctor -v
          flutter build windows --debug

          cd build\windows\x64
          tree /F

      - name: Test MacOS build
        if: matrix.os == 'macos-latest'
        working-directory: minisound/example/
        run: |
          flutter doctor -v
          flutter build macos --debug

          cd build\macos\x64
          tree
