name: Test Build on All Platforms

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^3.11.0"

      - name: Set up Linux dependencies 
        uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.os == 'ubuntu-latest'
        with:
          packages: clang libgtk-3-dev xvfb pulseaudio

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v4 
        with:
          channel: stable
          cache-sdk: true
          cache: true

      - name: Test Linux build
        if: matrix.os == 'ubuntu-latest'
        working-directory: minisound/example/
        run: |
          flutter build linux --debug

          tree build/linux/x64

          xvfb-run -w0 build/linux/x64/debug/bundle/example &
          sleep 10 && kill -TERM $!

      - name: Test Windows build
        if: matrix.os == 'windows-latest'
        working-directory: minisound/example/
        run: |
          flutter build windows --debug

          cd build\windows\x64
          tree /F
          cd -

          $PROC = Start-Process -FilePath build\windows\x64\runner\Debug\example.exe -PassThru
          Start-Sleep -Seconds 10
          $PROC.CloseMainWindow()

      - name: Test iOS build
        if: matrix.os == 'macos-latest'
        working-directory: minisound/example/
        run: |
          flutter build ios --debug --no-codesign

          find build/ios/Build/ -print

      - name: Test MacOS build
        if: matrix.os == 'macos-latest'
        working-directory: minisound/example/
        run: |
          flutter build macos --debug

          find build/macos/Build/ -print

          build/macos/Build/Products/Debug/example.app/Contents/MacOS/example &
          sleep 10 && kill -TERM $!


      - name: Get Flutter info
        if: failure()
        run: flutter doctor -v
