name: Test Build on All Platforms

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    strategy:
      matrix:
        os: 
          # - ubuntu-latest
          - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^3.11.0"

      - name: Set up Linux Flutter dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update -y && sudo apt-get install -y clang libgtk-3-dev

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v4 
        with:
          channel: stable

      - name: Test Linux build
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: minisound/example/
        run: |
          flutter doctor -v
          flutter build linux --debug

      - name: Test Windows build
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: minisound/example/
        run: |
          flutter doctor -v
          flutter build windows --debug

          cd build\windows\x64
          tree /F

          # Get-ChildItem -Path "build\windows\x64" -File -Recurse | ForEach-Object {
          #     Write-Host "===== FILE: $($_.FullName) ====="
          #     $bytes = [System.IO.File]::ReadAllBytes($_.FullName)
          #     if ($bytes.Length -gt 32768) {
          #         $text = [System.Text.Encoding]::UTF8.GetString($bytes, 0, 32768)
          #         Write-Host $text
          #         Write-Host "[truncated from $($bytes.Length) bytes...]"
          #     } else {
          #         Get-Content $_.FullName -Raw
          #     }
          #     Write-Host "===== EOF =====\n\n"
          # }

