name: Test Build on All Platforms

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:
    strategy:
      matrix:
        os: 
          # - ubuntu-latest
          - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "^3.11.0"

      - name: Set up Linux Flutter dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update -y && sudo apt-get install -y clang libgtk-3-dev

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v4 
        with:
          channel: stable

      - name: Test Linux build
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: minisound/example/
        run: |
          flutter doctor -v
          flutter build linux --debug

      - name: Test Windows build
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: minisound/example/
        continue-on-error: true
        run: |
          flutter pub get
          flutter build windows --debug --verbose
          for /r "minisound\example\build\windows\x64" %%F in (*) do (
              echo ===== FILE: %%F =====
              type "%%F"
              echo ===== EOF =====
          )

