name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1 

      - name: Analyze the package
        uses: axel-op/dart-package-analyzer@v3
        with:
          relativePath: minisound/
          # githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Check scores
        env:
          SCORE: ${{ steps.analysis.outputs.total }}
          SCORE_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          if [ $SCORE -lt $SCORE_MAX ]; then
            echo Score too low ($SCORE/$SCORE_MAX)!
            exit 1
          fi

      # // TODO!!! do something to publish all the packages

      # - name: Publish
      #   run: dart pub publish --force
